import * as path from 'path';
import * as fs from 'fs';

const THUMB_CACHE_DIR = '.thumb-cache';

/**
 * Thumbnail service using Electron's native image capabilities.
 * For now, returns a placeholder — actual thumbnails will be generated
 * in the renderer process using Canvas API (built into Chromium).
 *
 * The IPFS approach: send the file path to renderer, renderer creates
 * thumbnail via Canvas, sends back for caching.
 */
export interface ThumbnailResult {
  /** Local file path to the source image */
  filePath: string;
  /** Cached thumbnail path (if available) */
  cachePath?: string;
}

/**
 * Return the file path for the renderer to generate a thumbnail.
 * The actual thumbnail generation happens on the renderer side
 * using HTML Canvas (fast and zero native dependencies).
 */
export function getThumbnailPath(imagePath: string, cacheRoot: string): ThumbnailResult {
  const hash = Buffer.from(imagePath).toString('base64url');
  const cacheDir = path.join(cacheRoot, THUMB_CACHE_DIR);
  const cacheFile = path.join(cacheDir, `${hash}.jpg`);

  if (fs.existsSync(cacheFile)) {
    return { filePath: cacheFile, cachePath: cacheFile };
  }

  // Return source path — renderer will generate and cache
  return { filePath: imagePath };
}

/**
 * Save a thumbnail generated by the renderer.
 */
export function saveThumbnail(imagePath: string, cacheRoot: string, data: Buffer): string {
  const hash = Buffer.from(imagePath).toString('base64url');
  const cacheDir = path.join(cacheRoot, THUMB_CACHE_DIR);

  if (!fs.existsSync(cacheDir)) {
    fs.mkdirSync(cacheDir, { recursive: true });
  }

  const cacheFile = path.join(cacheDir, `${hash}.jpg`);
  fs.writeFileSync(cacheFile, data);
  return cacheFile;
}

/**
 * Get image dimensions from a file (reads just the header).
 */
export function getImageDimensionsFromBuffer(buf: Buffer): { width: number; height: number } | null {
  // JPEG SOF0 marker
  if (buf[0] === 0xFF && buf[1] === 0xD8) {
    let i = 2;
    while (i < buf.length - 1) {
      if (buf[i] !== 0xFF) break;
      const marker = buf[i + 1];
      i += 2;
      if (marker === 0xC0 || marker === 0xC2) {
        i += 3; // skip precision and 2 bytes each
        return {
          height: (buf[i] << 8) | buf[i + 1],
          width: (buf[i + 2] << 8) | buf[i + 3],
        };
      }
      const length = (buf[i] << 8) | buf[i + 1];
      i += length;
    }
  }

  // PNG IHDR
  if (buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4E && buf[3] === 0x47) {
    return {
      width: (buf[16] << 24) | (buf[17] << 16) | (buf[18] << 8) | buf[19],
      height: (buf[20] << 24) | (buf[21] << 16) | (buf[22] << 8) | buf[23],
    };
  }

  return null;
}
